### ISSUE TITLE
'BINDIR' in Prefab dir paths not correctly cofigured

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/prefab9#11]
`pr.core.dir_paths['BINDIR'] = '/opt/bin'`
Should be the same as `j.dirs.BINDIR = '/opt/jumpscale9/bin'`

**Comment by john-kheir** [comment]
![errrrr](https://user-images.githubusercontent.com/15011431/27259665-a29ed444-5418-11e7-9312-12cf57da760b.png)

**Comment by alichaddad** [comment]
Should be fixed after https://github.com/Jumpscale/core9/commit/0c56f0a9b001740f8f52de691732831728c5cd78
