### ISSUE TITLE
Add auto-restart option to atyourservice.configure(restart=True)

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#136]
#### Installation information

- jumpscale version: 9.3.0

#### Detailed description

After executing `ays_host.prefab.js9.atyourservice.configure()` you need to restart AYS server in order to make the changes effective.

FR:
- Let do `prefab.js9.atyourservice.configure()` this restart automatically by default: `restart=True`
- Add an argument that allows to disable this automatic restart, `restart=False`

**Comment by yveskerwyn** [comment]
@hossamabdullah @rkhamis please merge into 9.2.1

**Comment by rkhamis** [comment]
Done
