### ISSUE TITLE
Add auto-restart option to portal_host.prefab.web.portal.configure()

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#137]
#### Installation information

- jumpscale version: 9.3.0

#### Detailed description

After executing `portal_host.prefab.web.portal.configure()` you need to restart portal in order to make the changes effective.

FR:
- Let do `portal_host.prefab.web.portal.configure()` this restart automatically by default: `restart=True`
- Add an argument that allows to disable this automatic restart, `restart=False`

**Comment by yveskerwyn** [comment]
@hossamabdullah @rkhamis please merge into 9.2.1

**Comment by rkhamis** [comment]
Done
