### ISSUE TITLE
Allow to disable restart of portal when executing prefab.js9.atyourservice.configure_portal()

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#138]
#### Installation information

- jumpscale version: 9.3.0

#### Detailed description

For consistency with https://github.com/Jumpscale/prefab9/issues/136 and https://github.com/Jumpscale/prefab9/issues/137 add the option to disable automatic restart of the portal when executing `portal_host.prefab.js9.atyourservice.configure_portal()`:

By default (current behavior) the portal is restarted, add an optional argument at the end of the signature to disable this: `restart: False`

**Comment by yveskerwyn** [comment]
@hossamabdullah @rkhamis please merge into 9.2.1

**Comment by rkhamis** [comment]
Done
