### ISSUE TITLE
Interaction in tmux required when adding AYS templates

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#156]
#### Installation information

- jumpscale version: 9.2.1
- operating system: Ubuntu

#### Detailed description

When executing `ays.templates.addTemplates("https://github.com/openvcloud/ays_templates", branch)` you are required to enter `yes` in the tmux session of the AYS server:

![screen shot 2018-01-11 at 17 54 06](https://user-images.githubusercontent.com/13795109/34836566-8ea57cbc-f6f8-11e7-933c-c506a4dc908a.png)

#### Steps to reproduce

```python
import os
app_id = os.environ["APP_ID"]
secret = os.environ["SECRET"]

public_ays_url = "http://185.193.143.74:5000"

scope = 'user:memberof:{}'.format(ays_clients_org_name)
jwt = j.clients.itsyouonline.get_jwt(app_id, secret, scope=scope)
ays = j.clients.ays.get_with_jwt(public_ays_url, jwt)
ays.templates.addTemplates("https://github.com/openvcloud/ays_templates", branch)
```

**Comment by arahmanhamdy** [comment]
https://github.com/Jumpscale/lib9/issues/139

**Comment by yveskerwyn** [comment]
@arahmanhamdy Did we add this to 9.2.1 already?
