### ISSUE TITLE
Implement prefab modules for blockchains

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/prefab9#192]
As part of https://docs.greenitglobe.com/gig/org_development/issues/60 we need to implement prefabe modules to install/configure 4 of the blockchain implementations.

- Build/Install tfchain (call j.tools.prefab.local.apps.tfchain until we move it)
- Build/install Bitcoin 
- Build/install Ethereum
- Build/Install Ripple 

The main goal of implementing the prefab modules is to allow us to build flists for these applications.

**Comment by ahmedelsayed-93** [comment]
verified

**Comment by ahmedelsayed-93** [comment]
closed by mistake
