### ISSUE TITLE
Prefab9 clean method remove tmp directory 

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/prefab9#48]
As shown in the screenshot , we found that prefab clean method delete tmp directory 

![selection_553](https://user-images.githubusercontent.com/24386802/30921319-809b3e72-a3a6-11e7-96ab-c69f8ef8f588.png)

## Software Version 
c85a27f2e4b1bdb51ed772e34b8cdac4a25c03f4

**Comment by john-kheir** [comment]
Verified
