### ISSUE TITLE
prefab.system.ssh.authorize() fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#89]
#### Installation information

- jumpscale version: 9.3.0 (master)

#### Detailed description

As discussed with @rkhamis, executing the following fails:
```python
...
iyo_user = j.clients.itsyouonline.get_user(app_id, secret)
pubkey = iyo_user.public_keys.get("default")
...
prefab = ays_server_93.prefab
prefab.system.ssh.authorize("cloudscalers", pubkey.model["publickey”])
```

#### Relevant stacktraces

```python
Input: ERROR: could not find config key:dirs in executor:{'ays': {'production': True, 'oauth': {'jwt_key': 'MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv', 'client_secret': '', 'client_id': '', 'redirect_uri': 'https://locahost:5000', 'organization': 'testorg'}}} ((type:input.error)
```

**Comment by khaledkbadr** [comment]
The issue is with your configuration not with the `authorize` method. The config file does not have the right data.

**Comment by yveskerwyn** [comment]
Can you elaborate a little?

What data is missing @khaledkbadr?

**Comment by khaledkbadr** [comment]
> What data is missing @khaledkbadr?

As stated in the error provided, the `jumpscale dirs`  are missing from the config.

> The real questions is, why is it missing?

Can you provide the available config file?

> And what do I need to do to make sure it is not missing?

If the config file is missing it will be regenerated automatically when starting a `js9` shell.

**Comment by yveskerwyn** [comment]
@khaledkbadr, it actually works, just tested using the below code.

However when executing the `prefab.system.ssh.authorize()` you get FALSE as return value, while the key actually got added successfully for both the cloudscaler and root user.

Provision a new server:
```python
import os
app_id = os.environ["APP_ID"]
secret = os.environ["SECRET"]
url = "se-gen-1.demo.greenitglobe.com"
client = j.clients.openvcloud.get(app_id, secret, url)
account = client.account_get("Account_of_Yves", create=False) 
vdc = account.space_get("js93-space", "se-gen-1")
import os; path = os.path.expanduser("~/.ssh/mykey")
j.clients.ssh.load_ssh_key(path=path, create_keys=True)
new_server = vdc.machine_create("new-server", "mykey", memsize=4, vcpus=2)
```

Adding my default public key to authorized_keys for both cloudscalers and root:
```python
iyo_user = j.clients.itsyouonline.get_user(app_id, secret)
pubkey = iyo_user.public_keys.get("default")
prefab = new_server.prefab
prefab.system.ssh.authorize("cloudscalers", pubkey.model["publickey"])
prefab.system.ssh.authorize("root", pubkey.model["publickey"])
```
