### ISSUE TITLE
Allow  to use prefab.web.portal.configure() to set membership to distinct value

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#90]
#### Installation information

- jumpscale version: 9.2.0

Also see: https://github.com/Jumpscale/prefab9/issues/87

#### Detailed description

Currently if you use `prefab.web.portal.configure()` to configure the OAuth settings of JumpScale Portal you cannot set a value for `memberof` in `oauth.client_scope` that is different from the value that gets set for `oauth.client_scope`.

Here's the example of a what we typically try to achieve:

![screen shot 2017-11-23 at 10 46 59](https://user-images.githubusercontent.com/13795109/33167521-128d9000-d03e-11e7-9da0-c3c5ca6f58f0.png)

In this example:
- Only users that are member of the `artilium-dev2.ays-server-clients.ays-portal-users` organization can login to the AYS Portal
- Only clients that have access to an API access key of the `artilium-dev2.ays-server-clients` can access the AYS RESTful server

This example configuration can only be created MANUALLY; `refab.web.portal.configure()` doesn't allow you to do so.

**Comment by yveskerwyn** [comment]
@khaledkbadr I was unable to verify this because of a new issue: https://github.com/Jumpscale/prefab9/issues/103

**Comment by khaledkbadr** [comment]
@yveskerwyn  #103 should be fixed now
