### ISSUE TITLE
file_size sometime return 0

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/prefab9#95]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description
Sometime the method `file_size` from PrefabCore module returns 0 while the file has actually a different size.

#### Steps to reproduce
I happend randomly. 
I got the error when trying to install golang or nodejs. 
Sometimes is works, sometimes the size returned is 0

**Comment by khaledkbadr** [comment]
I hardened the code in https://github.com/Jumpscale/prefab9/commit/caddd26d751ea1a03685819fec1939fefd09a337 to raise an error if something wrong happened while executing the command here.
