### ISSUE TITLE
Add a method to configure ays api console in ays prefab

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/prefab9#99]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu

#### Detailed description
We need to make a way in the PrefabAtyourservice to configure the AYS API Console separately from the protal

![image](https://user-images.githubusercontent.com/6059889/33308704-2aa5ca1a-d424-11e7-9ae9-498aeaeae7f8.png)

**Comment by khaledkbadr** [comment]
`j.tools.prefab.local.js9.atyourservice.configure_api_console(host="localhost", port=5000)` method was added to resolve the issue

**Comment by zaibon** [comment]
@khaledkaram why are we forcing http only in the new method you added to solve this issue?

**Comment by khaledkbadr** [comment]
> why are we forcing http only in the new method you added to solve this issue?

It was the same thing as it was in the raml file, I just added the ability to add the domain itself. Other way to do it, to take whatever the user gives and put it in there or add another param for it with `http` as default

**Comment by zaibon** [comment]
I think the correct way to do this is to receive an URL as argument to this method. Cause you could have you api not bind to the root of your domain.
